### ISSUE TITLE
Can the outputPath be an array?

### ISSUE THREAD

**Issue by ghost** [klaascuvelier/gulp-copy#11]
I am looking to copy global .scss partials into multiple themes before running a compile task.

It seems that rather than iterating through each path in the array, it is concatenating all of the paths in the array and outputting the contents into that new path.

<pre>
<code>
gulp.task('copySCSS', function () {
  var multipleDestinations = [
    "theme1/base/",
    "theme2/base/",
    "theme3/base/"
  ];
  return gulp
     .src("base/" + {,*/}*.scss)
     .pipe(copy(multipleDestinations, {prefix: 1}));
});
</code>
</pre>

Thanks in advance.

**Comment by landsman** [comment]
ping

**Comment by klaascuvelier** [comment]
@ghost, @landsman apologies for my slow response here.

I currently do not see a way to add this to the plugin, as the idea of this plugin is to copy files and use the new destination paths as "sources" for the next `pipe` for gulp. So each input file will return 1 new output fill.

If I'd make the destination an array, then 1 input file should return multiple output files, I don't think this is possible with the current architecture (using `through2`) and even makes sense for this plugin.

As a work around you could try using this trick;
Define all your output paths in an array, and generate gulp tasks for every output path:
```
const outputPaths = ['path1', 'path2', 'path3'];
outputPaths.forEach((path, index) => {
	gulp.task(`copy-${index}`, () => {
		return gulp
			.src('./source.txt')
			.pipe(copy(path, {options}));
	});
});

gulp.task('copy-to-multiple-paths', outputPaths.map((path, index) => `copy-${index}`));
```
