### ISSUE TITLE
`fs.existsSync()` is deprecated since Node 4.x. Use `fs.statSync()` or `fs.accessSync()` instead.

### ISSUE THREAD

**Issue by kadishmal** [klaascuvelier/gulp-copy#16]
Since Node 4.x `fs.existsSync()` is [deprecated](https://nodejs.org/docs/latest-v4.x/api/fs.html#fs_fs_existssync_path). Use `fs.statSync()` or `fs.accessSync()` instead.

I will send a PR if @klaascuvelier is still active.

**Comment by klaascuvelier** [comment]
Go ahead!
I'll verify and test when your PR is ready
