### ISSUE TITLE
Mark this package as deprecated in the README.md

### ISSUE THREAD

**Issue by benderTheCrime** [klaascuvelier/gulp-copy#17]
Thanks for making this package! I used it for quite some time. However, this package is unnecessary unless you want to keep some depth, which is possible to accomplish by simply editing the destination directory of the `gulp.dest` to the target path you desire:

```
    const DIST = path.join(process.cwd(), 'some/non-existent/directory');
    gulp.task('copy', function() {
        return gulp.src(SRC).pipe(gulp.dest(DIST));
    });
```

I think it's more prudent to recommend not including this package to do what Gulp already has the capacity to do on it's own.

**Comment by klaascuvelier** [comment]
Yeah, I started working on this package again a few days back and I was wondering in which case it could be still valid/useful.
I'll finish my version with some fixes, but will make it more clear what the use case, which regular `src()` and `dest` can't do, for this is.

**Comment by benderTheCrime** [comment]
Thanks!
