### ISSUE TITLE
npm version mismatch with github

### ISSUE THREAD

**Issue by simon-pestell-gw** [klaascuvelier/gulp-copy#19]
Hi,

We have come across a problem using the npm package for gulp-copy. We have our package.json setup to pull down 0.0.2 however it seems to be pulling down 0.0.1.

The output suggests its pulled down 0.0.2,
 gulp-copy@0.0.2 
│ ├─┬ gulp-util@2.2.20 
│ │ ├─┬ chalk@0.5.1 

However when we look at the code, we can see it is actually pulling down 0.0.1.

We know this because there is a bug in createDestination where it tries to create an empty folder and we can see that you have fixed this in 0.0.2. However it is still broken in the npm package.

If you could take a look at that and get it updated, that would be great!

**Comment by klaascuvelier** [comment]
I'll fix this asap.

**Comment by phamdt** [comment]
any progress on this?

**Comment by klaascuvelier** [comment]
@phamdt the package is currently at version `1.0.0` in which all issues should be resolved.
Can you upgrade and check if everything is fixed for you?
