### ISSUE TITLE
Other tasks doesn't pipe with copy

### ISSUE THREAD

**Issue by raphaelgoetter** [klaascuvelier/gulp-copy#2]
Hello,

This code doesn't work : 

```
gulp.task('html', function () {
	return gulp.src(src + '*.html')
		
		.pipe(copy(dest + '.'))
	
		// Minifies HTML but keeps one whitespace
		.pipe(htmlmin())
	
		// Add a CSS version hash into the HTML link
		.pipe(rev())
	
		.pipe(gulp.dest(dest))
});
```

The file is copied to destination, but htmlmin and rev task do not execute.

Have you an explanation ?

**Comment by SamVerschueren** [comment]
htmlmin handles the copy itself.

```JavaScript
return gulp.src(src + '*.html')
        .pipe(htmlmin())
        .pipe(gulp.dest(dest));
```

**Comment by esbenp** [comment]
+1

**Comment by klaascuvelier** [comment]
I am with @SamVerschueren on this. 
The plugin only copies files (which you can just do with `gulp.src` and `gulp.dest` btw). If you add other plugins to the stream, you have to do `gulp.dest` at the end to see the result
