### ISSUE TITLE
DO NOT USE THIS PROJECT

### ISSUE THREAD

**Issue by mosfet1kg** [klaascuvelier/gulp-copy#21]
You can copy any files without this project.
Refer to following code
```
gulp.task('imgCopy', function(){
  return gulp.src( src + '/images/**/*')
    .pipe( gulp.dest( dist + '/images/') );
});
```

**Comment by klaascuvelier** [comment]
The readme clearly states this project is only useful for certain use cases.

**Comment by Stevemoretz** [comment]
That doesn't work everywhere it gets all the files and puts it all in a folder
