### ISSUE TITLE
NSP Check - Gulp update to 4.0.0

### ISSUE THREAD

**Issue by nvwebd** [klaascuvelier/gulp-copy#31]
I'm trying to create a PR to update the gulp dep to the latest version and mitigate the nsp check fail.

Are you going to update the dep or can I create a PR?

**Comment by acconrad** [comment]
@nvwebd I'm happy to tackle this too, this is a major security blocker (`minimatch` and `lodash` were upgraded in the newer version of `vinyl-fs` which is a dependency on `gulp` that was properly secured in the `4.0.0` release of gulp) so it would be great if we could get this upgrade out ASAP

**Comment by klaascuvelier** [comment]
Version `4.0.0` with Gulp 4 support has been published.
Thank you for implementing the changes @acconrad
