### ISSUE TITLE
This usage description doesn't work

### ISSUE THREAD

**Issue by maniac0s** [klaascuvelier/gulp-copy#35]
[12:34:19] ReferenceError: outputPath is not defined

**Comment by klaascuvelier** [comment]
You are right, thanks for pointing that out.
I added the undefined variable and it should work now.

You can also have look in the examples folder; I added that to the README as well :)

**Comment by maniac0s** [comment]
Thanks but I think you made a typo in the readme:
outputPath not outputPut ;)

**Comment by klaascuvelier** [comment]
Oops! I guess I should have copy-pasted that variable name :D 

Fixed it!
