### ISSUE TITLE
Deprecated gulp-util dependency

### ISSUE THREAD

**Issue by petermonte** [klaascuvelier/gulp-copy#38]
As per this [article](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) [Gulp-Util](https://www.npmjs.com/package/gulp-util) is no longer maintained by newer version of Node, therefore I'm registering the issue.

**Comment by klaascuvelier** [comment]
@petermonte thanks for bringing this to my attention. I'll take this up asap.
Or anyone else can make a PR ;)

**Comment by klaascuvelier** [comment]
Oh no worries, it was not specifically targeted to you. Just anyone :)

**Comment by klaascuvelier** [comment]
Hey, wait as second @petermonte; what version of the plugin are you on?
It appears `gulp-util` was already removed here: https://github.com/klaascuvelier/gulp-copy/commit/ffde3643a7983aef5aceb51bdf28651d3e093599

There's no mention of `gulp-util` in `package-lock.json` either, so I don't think you should have any errors if you're on the latest version.

**Comment by petermonte** [comment]
so my package file is declaring this:

```json
"gulp-copy": "^1.1.0",
"gulp-util": "^3.0.8",
```
when running the command `npm ls gulp-util` your plugin came in the results. But now that you mention,  after the entire library was updated **Gulp-Copy** seems to lo longer get into the list:

```
├─┬ gulp-include@2.3.1
│ └── gulp-util@2.2.20 
└─┬ gulp-sass@3.2.0
  └── gulp-util@3.0.8 
```

Guess this is my bad. Sorry for that :)

**Comment by klaascuvelier** [comment]
Great you got this resolved!

Have a great weekend!

**Comment by petermonte** [comment]
thanks. likewise.
