### ISSUE TITLE
Deprecated or not?

### ISSUE THREAD

**Issue by SamVerschueren** [klaascuvelier/gulp-copy#4]
Am I mistaken or can this be done natively by gulp itself? Does gulp-copy offer more/better functionality then something like

```JavaScript
gulp.src(['assets/images/**/*'])
    .pipe(gulp.dest('dist/assets/images'));
```

**Comment by nrdobie** [comment]
Here is an example of the copy task for an AngularJS project. If you use `gulp.dest` it will only use directories found via the wild cards. What gulp-copy does is preserve the entire path and by using prefix it will remove x number of directories from the beginning of the path, in my case just the `src/`. It really depends on your use case for if this is useful or not.

```js
gulp.task('copy', function () {
    return gulp.src([
           'src/index.html',
           'src/templates/**/*.html',
           'src/images/**/*'
           'src/fonts/**/*'
        ])
        .pipe(copy('build', {prefix: 1}));
});
```

**Comment by SamVerschueren** [comment]
Ok, thanks for your explanation @nrdobie

**Comment by klaascuvelier** [comment]
Thanks for explaining @nrdobie!

**Comment by kimaldis** [comment]
If I can add, this seems to be the easiest way to copy files to an absolute path. dest won't do this. So for me it's useful.
