### ISSUE TITLE
Copy .hidden files

### ISSUE THREAD

**Issue by TehZarathustra** [klaascuvelier/gulp-copy#5]
Is it possible? Thanks.

**Comment by klaascuvelier** [comment]
@TehZarathustra it does work if you explicitly add the dot file (or dot pattern) to your sources, like this:
````
    gulp.task('default', function () {
    gulp
        .src(['test-stuff/*', 'test-stuff/.*'])
        .pipe(gulpCopy('./copied'));
    });
````

**Comment by TehZarathustra** [comment]
thanks a lot!

**Comment by tfmontague** [comment]
@TehZarathustra @klaascuvelier 

There are 4 combinations needed to look for all hidden and non-hidden files.
Hidden files can also be in hidden folders. 

`**/*` - copy all folders, and their files
`**/.*` - copy all folders, and their hidden files
`.**/*` - copy all hidden folders, and their files
`.**/.*` - copy all hidden folders, and their hidden files

```
gulp.task('default', function () {
    gulp
      .src(['**/*', '**/.*', '.**/*', '.**/.*'])
      .pipe(gulpCopy('./copied'));
  });
```

Any thoughts on adding a `hidden` option?
Or having `*` include hidden files?

**Comment by afinnell** [comment]
From what I can tell this isn't a gulp-copy issue but rather a issue with gulp.src(). I too would like `**/*.*'`to find ALL files, as that's literally what is being said. Perhaps what is needed is partial regular expressions like: `**/*[.]?*`

**Comment by agurtovoy** [comment]
For anyone who is brought here by Google, here's an easer way: `gulp.src( "**/*", { dot: true } )`.

**Comment by klaascuvelier** [comment]
Thanks @agurtovoy
