### ISSUE TITLE
Does the typo usage have a extra `$`?

### ISSUE THREAD

**Issue by titancat** [klaascuvelier/gulp-copy#6]
## Usage
```
return gulp.src(sourceFiles)
  .pipe($.copy(outputPath, options));
```
If I copy the code above, I got error ` ReferenceError: $ is not defined`.
If I delete `$.`, the code works.
Does  the typo usage have a extra `$` or I make a mistake for `$`?

**Comment by klaascuvelier** [comment]
My bad, it's not a good example. I used to use [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins) to automatically load all plugins, and I used the `$` as a variable name.
I'll update the example.

**Comment by klaascuvelier** [comment]
Fixed
