### ISSUE TITLE
can I copy files from multiple locations?

### ISSUE THREAD

**Issue by yahyaKacem** [klaascuvelier/gulp-copy#8]
Hi, I need to do something like this:

    gulp.task('copyFonts', function () {
      var fontsFilesToCopy = [
        "src/fonts/*",
        "src/libs/font-awesome/fonts/*",
        "src/libs/bootstrap/dist/fonts/*"
      ];
      return gulp.src(fontsFileToCopy).pipe(copy('build', {prefix: 1}));
    });

But I need all the files under the 'build/fonts' folder so the prefix needs to be different for each group of files:

  - "src/fonts/*" => prefix = 1,
  - "src/libs/font-awesome/fonts/*" => prefix = 3,
  - "src/libs/bootstrap/dist/fonts/*" => prefix = 4

Is it possible to pipe files to this task like multiple copy that pipes to each other, or is there a way to accomplish this?
Thanks in advance.

**Comment by seminull** [comment]
Hi @yahyaKacem 

Will this not work for you?

```javascript
gulp.task('copyFonts', function () {
  var fontsFilesToCopy = [
    "src/fonts/*",
    "src/libs/font-awesome/fonts/*",
    "src/libs/bootstrap/dist/fonts/*"
  ];
  return gulp.src(fontsFileToCopy).pipe(gulp.dest('./build'));
});
```
